#!/usr/bin/env python

# Referenced from modules/tinyexr/SCsub

Import("env")
Import("env_modules")

env_toml = env_modules.Clone();

thirdparty_obj = []

thirdparty_dir = "#thirdparty/toml/"
thirdparty_sources = [
    # "toml.hpp"
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_toml.Prepend(CPPPATH=[thirdparty_dir])

env_thirdparty = env_toml.Clone()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

# Godot source files

module_obj = []

env_toml.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

env.Depends(module_obj, thirdparty_obj)
